### PR TITLE
parse multiple pages of gitlab repos

### PR DESCRIPTION
**Pull request by mastertinner**

### CODE REVIEW

**Comment by knownasilya** [comment]
Published in the ecosystem as 1.2.0

**Comment by mastertinner** [comment]
Awesome, thanks!

**Comment by mastertinner** [comment]
@knownasilya, can you also publish it to npm, please?

**Comment by knownasilya** [comment]
Sweet, I had publish rights to that one. All set.

**Comment by mastertinner** [comment]
:+1: , thanks!

**Pull request merged**
