### PR TITLE
Use latest strider-git

### PR DESCRIPTION
**Pull request by oliversalzburg**

### CODE REVIEW

**Comment by knownasilya** [comment]
I'm going to wait on merging this, since I just merged your other change to strider-git

**Comment by oliversalzburg** [comment]
Yeah, it was just that I noticed that strider-gitlab installs another instance of strider-git, leading to a bit of confusion in regard to which strider-git is doing what.

**Comment by knownasilya** [comment]
Updated strider-git to 0.2.3 so you can update this PR

**Comment by oliversalzburg** [comment]
@knownasilya Done

**Pull request merged**
