### PR TITLE
Added unit test cases for api and webapp

### PR DESCRIPTION
**Pull request by saraf**
Added unit tests using nock to mock responses
from a real gitlab server. Steps for adding
to the cases written in README.md in the test
directory.

Also, bumped up version for mocha and superagent,
added dependency for nock in package.json

### CODE REVIEW

**Comment by saraf** [comment]
Will commit the fixes for the failing tests shortly.

**Comment by knownasilya** [comment]
This is all set?

**Comment by saraf** [comment]
Yes, done!

**Comment by saraf** [comment]
Some more tests need to be added, but the tests for webapp and api are done - can be merged. Some tests are marked pending as I am not sure what the expected result should be.

**Comment by knownasilya** [comment]
Sweet, I setup travis, so that should work now.

**Comment by saraf** [comment]
:+1:

**Pull request merged**
